# Generated by Django 3.2.7 on 2021-10-30 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dicho',
            fields=[
                ('id_table', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('file_id', models.IntegerField(null=True)),
                ('author', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=200, null=True)),
                ('recognized_text', models.TextField(max_length=6000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id_file', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('file_type', models.CharField(max_length=15)),
                ('file_attached', models.BinaryField(null=True)),
                ('file_uri', models.CharField(max_length=500, null=True)),
            ],
        ),
    ]
