# Generated by Django 3.2.7 on 2021-10-30 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speechToText', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dicho',
            name='recognized_text',
            field=models.CharField(max_length=6000),
        ),
    ]
