# Generated by Django 3.2.7 on 2021-10-01 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speechToText', '0002_alter_dicho_id_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='dicho',
            name='id_file',
            field=models.IntegerField(null=True),
        ),
    ]
